//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Resources;

namespace nanoFramework.Fire
{
    
    internal partial class Resource
    {
        private static ResourceManager manager;
        internal static ResourceManager ResourceManager
        {
            get
            {
                if ((Resource.manager == null))
                {
                    Resource.manager = new ResourceManager("nanoFramework.Fire.Resource", typeof(Resource).Assembly);
                }
                return Resource.manager;
            }
        }
        internal static nanoFramework.UI.Font GetFont(Resource.FontResources id)
        {
            return ((nanoFramework.UI.Font)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [SerializableAttribute()]
        internal enum FontResources : short
        {
            consolas_regular_16 = 10023,
        }
    }
}
